import Accordion from "./components/accordion";
import Agreement from "./components/agreement";
import Appearance from "./components/appearance";
import Loading from "./components/loading";
import Modal from "./components/modal";
import NavbarToggle from "./components/navbar-toggle";
import ToScroll from "./components/to_scroll";
import SeeMore from "./components/see_more";
import StretchTextarea from "./components/stretch_textarea";
import Snackbar from "./components/snackbar";
import Tab from "./components/tab";
import TextCounter from "./components/text_counter";
import Toggle from "./components/toggle";

(new Accordion()).initialize();
(new Agreement()).initialize();
(new Appearance()).initialize();
(new Loading()).initialize();
(new Modal()).initialize();
(new NavbarToggle()).initialize();
(new ToScroll()).initialize();
(new SeeMore()).initialize();
(new StretchTextarea()).initialize();
(new Snackbar()).initialize();
(new Tab()).initialize();
(new TextCounter()).initialize();
(new Toggle()).initialize();
